name: Post Release Tasks

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true

jobs:
  docker-build-and-oush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Build and Push
        run: |
          echo "Building Docker image for version ${{ inputs.version }}"
          docker build -tghcr.io/bognarbalazs/gatekeeper-metrics-reporter:${{ inputs.version }} -t ghcr.io/bognarbalazs/gatekeeper-metrics-reporter:latest --build-arg APP_VERSION=${{ inputs.version }} .
          docker push ghcr.io/bognarbalazs/gatekeeper-metrics-reporter:${{ inputs.version }}
          docker push ghcr.io/bognarbalazs/gatekeeper-metrics-reporter:latest
